### ISSUE TITLE
"xx"does not contain an application bundle, so it cannot be installed on Device

### ISSUE THREAD

**Issue by ipad4** [Magic-Unique/IPASigner#1]
"xx"does not contain an application bundle, so it cannot be installed on Device

**Comment by Magic-Unique** [comment]
Can u provide log with `--verbose`?

**Comment by ipad4** [comment]
> Can u provide log with `--verbose`?

Reading profile...
Reading profile: iOS Team Provisioning Profile: *
Reading identities...
/usr/bin/security find-identity -v -p codesigning
      1) .....
      2) .....
      
 2 valid identities found
Create temp directory: /var/folders/sm/sj148b_50fs6mfxcfw44mdd00000gn/T/1641208782.799792
Unpackage IPA: /Users/abc/Downloads/test.ipa
/usr/bin/mktemp -d
    /var/folders/sm/sj148b_50fs6mfxcfw44mdd00000gn/T/tmp.bvrkGkGa
CodeSign: XXX.app
    Embedded provision profile: iOS Team Provisioning Profile: *
    Add /var/folders/sm/sj148b_50fs6mfxcfw44mdd00000gn/T/1641208782.799792/Payload/XXX.app/Frameworks/widevine_cdm_secured_ios.framework
    Add /var/folders/sm/sj148b_50fs6mfxcfw44mdd00000gn/T/1641208782.799792/Payload/XXX.app/Frameworks/Module_Framework.framework
    Add /var/folders/sm/sj148b_50fs6mfxcfw44mdd00000gn/T/1641208782.799792/Payload/XXX.app/YYY.dylib
    Add /var/folders/sm/sj148b_50fs6mfxcfw44mdd00000gn/T/1641208782.799792/Payload/XXX.app/Frameworks/widevine_cdm_secured_ios.framework
    Sign XXX.app/Frameworks/Module_Framework.framework
    /usr/bin/codesign --verify --verbose --force --sign 6386A6AD25BBE2319105E6A40CC646AECB70E389 /var/folders/sm/sj148b_50fs6mfxcfw44mdd00000gn/T/1641208782.799792/Payload/XXX.app/Frameworks/Module_Framework.framework
        /var/folders/sm/sj148b_50fs6mfxcfw44mdd00000gn/T/1641208782.799792/Payload/XXX.app/Frameworks/Module_Framework.framework: replacing existing signature
        /var/folders/sm/sj148b_50fs6mfxcfw44mdd00000gn/T/1641208782.799792/Payload/XXX.app/Frameworks/Module_Framework.framework: signed bundle with Mach-O thin (arm64) [com.ios.xxx.modules]
    Sign XXX.app/YYY.dylib
    /usr/bin/codesign --verify --verbose --force --sign 6386A6AD25BBE2319105E6A40CC646AECB70E389 /var/folders/sm/sj148b_50fs6mfxcfw44mdd00000gn/T/1641208782.799792/Payload/XXX.app/YYY.dylib
        /var/folders/sm/sj148b_50fs6mfxcfw44mdd00000gn/T/1641208782.799792/Payload/XXX.app/YYY.dylib: replacing existing signature
        /var/folders/sm/sj148b_50fs6mfxcfw44mdd00000gn/T/1641208782.799792/Payload/XXX.app/YYY.dylib: signed Mach-O universal (armv7 arm64 arm64e) [YYY]
    Sign XXX.app/Frameworks/widevine_cdm_secured_ios.framework
    /usr/bin/codesign --verify --verbose --force --sign 6386A6AD25BBE2319105E6A40CC646AECB70E389 /var/folders/sm/sj148b_50fs6mfxcfw44mdd00000gn/T/1641208782.799792/Payload/XXX.app/Frameworks/widevine_cdm_secured_ios.framework
        /var/folders/sm/sj148b_50fs6mfxcfw44mdd00000gn/T/1641208782.799792/Payload/XXX.app/Frameworks/widevine_cdm_secured_ios.framework: replacing existing signature
        /var/folders/sm/sj148b_50fs6mfxcfw44mdd00000gn/T/1641208782.799792/Payload/XXX.app/Frameworks/widevine_cdm_secured_ios.framework: signed bundle with Mach-O thin (arm64) [com.google.widevine-cdm-secured-ios-2]
    Sign XXX.app
    /bin/chmod 777 /var/folders/sm/sj148b_50fs6mfxcfw44mdd00000gn/T/1641208782.799792/Payload/XXX.app/XXX
    /usr/bin/mktemp -d
        /var/folders/sm/sj148b_50fs6mfxcfw44mdd00000gn/T/tmp.yrDL4qtj
    /usr/bin/codesign --verify --verbose --force --sign 6386A6AD25BBE2319105E6A40CC646AECB70E389 --entitlements /var/folders/sm/sj148b_50fs6mfxcfw44mdd00000gn/T/tmp.yrDL4qtj/temp.entitlements /var/folders/sm/sj148b_50fs6mfxcfw44mdd00000gn/T/1641208782.799792/Payload/XXX.app
        /var/folders/sm/sj148b_50fs6mfxcfw44mdd00000gn/T/1641208782.799792/Payload/XXX.app: replacing existing signature
        /var/folders/sm/sj148b_50fs6mfxcfw44mdd00000gn/T/1641208782.799792/Payload/XXX.app: signed app bundle with Mach-O thin (arm64) [com.ios.xxx]
Package IPA: /Users/abc/Downloads/test.signed.ipa
Done!

**Comment by Magic-Unique** [comment]
How size of the `test.signed.ipa` ? According to this log, IPASigner was work well.

**Comment by Magic-Unique** [comment]
There is something wrong with Info.plist file ?

**Comment by ipad4** [comment]
> How size of the `test.signed.ipa` ? According to this log, IPASigner was work well.

test.ipa 108.2MB
test.signed.ipa 106.1MB

**Comment by Magic-Unique** [comment]
How about the other sign tools ? Its work ?

**Comment by ipad4** [comment]
> How about the other sign tools ? Its work ?

fastlane sigh resign test.signed.ipa is OK

**Comment by Magic-Unique** [comment]
Ok, i needs your ipa file to debug. Can u email me?
