### ISSUE TITLE
编译完成后运行失败

### ISSUE THREAD

**Issue by LeeeMooo** [Magic-Unique/IPASigner#3]
<img width="644" alt="image" src="https://user-images.githubusercontent.com/23691333/198460329-087f8c6c-7d5a-48e5-9f85-0a82d5f9e9b3.png">

- macos version 12.6 m1
- xcode version 14.0
请问怎么解决

**Comment by Magic-Unique** [comment]
sudo chmod 777 /usr/local/bin


这样试一试？

**Comment by LeeeMooo** [comment]
还是不行

**Comment by Magic-Unique** [comment]
可能是签名的问题，你打开 Console.app，打开 Mac 的日志，添加过滤 ipasigner，然后再终端执行一次 ipasigner，看看日志里有什么。

**Comment by LeeeMooo** [comment]
ASP: Security policy would not allow process

**Comment by Magic-Unique** [comment]
Mac 要关闭 SIP，或者到【设置】-【安全性与隐私】-【通用】允许运行 ipasigner

**Comment by LeeeMooo** [comment]
ok
